package com.plantcare.app.storage.greendao.model.v1;

import android.database.sqlite.SQLiteDatabase;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;
import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig plantObjectDaoConfig;
    private final DaoConfig kindObjectDaoConfig;
    private final DaoConfig kindToPlantObjectDaoConfig;

    private final PlantObjectDao plantObjectDao;
    private final KindObjectDao kindObjectDao;
    private final KindToPlantObjectDao kindToPlantObjectDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        plantObjectDaoConfig = daoConfigMap.get(PlantObjectDao.class).clone();
        plantObjectDaoConfig.initIdentityScope(type);

        kindObjectDaoConfig = daoConfigMap.get(KindObjectDao.class).clone();
        kindObjectDaoConfig.initIdentityScope(type);

        kindToPlantObjectDaoConfig = daoConfigMap.get(KindToPlantObjectDao.class).clone();
        kindToPlantObjectDaoConfig.initIdentityScope(type);

        plantObjectDao = new PlantObjectDao(plantObjectDaoConfig, this);
        kindObjectDao = new KindObjectDao(kindObjectDaoConfig, this);
        kindToPlantObjectDao = new KindToPlantObjectDao(kindToPlantObjectDaoConfig, this);

        registerDao(PlantObject.class, plantObjectDao);
        registerDao(KindObject.class, kindObjectDao);
        registerDao(KindToPlantObject.class, kindToPlantObjectDao);
    }

    public void clear() {
        plantObjectDaoConfig.getIdentityScope().clear();
        kindObjectDaoConfig.getIdentityScope().clear();
        kindToPlantObjectDaoConfig.getIdentityScope().clear();
    }

    public PlantObjectDao getPlantObjectDao() {
        return plantObjectDao;
    }

    public KindObjectDao getKindObjectDao() {
        return kindObjectDao;
    }

    public KindToPlantObjectDao getKindToPlantObjectDao() {
        return kindToPlantObjectDao;
    }

}
